apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: os-autoscaler-nodecleaner-role
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: os-autoscaler-nodecleaner-rolebinding
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: os-autoscaler-nodecleaner-role
subjects:
  - kind: ServiceAccount
    name: os-autoscaler-nodecleaner-account
    namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: os-autoscaler-nodecleaner-account
  namespace: kube-system
